# Generated by Django 5.2.16 on 2026-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('VENDEUR', 'Vendeur'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
