# Generated by Django 5.2.16 on 2026-07-31 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0003_commande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant', models.PositiveIntegerField()),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='commande.commande')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
