# Generated by Django 5.2.16 on 2026-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_commande_options_alter_lignecommande_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('REMBOURSEE', 'Remboursée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
