# Generated by Django 5.2.16 on 2026-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
