# Generated by Django 5.2.16 on 2026-08-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='phone',
            field=models.PositiveBigIntegerField(default=655318272),
        ),
    ]
