"""
Django settings for market project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'product',
    'inventory',
    'mouvement_stock',
    'categorie',
    'users',
    'authentication',
    'commande',
    'paiement'
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.AccessTokenBlacklistMiddleware'
]

ROOT_URLCONF = 'market.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# configuration du serveur de cache Redis 
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'PASSWORD': 'VOTRE_MOT_DE_PASSE', 
#         }
#     }
# }

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # Cache mémoire par défaut
        'LOCATION': 'unique-snowflake',
    }
}

# Essayer d'utiliser Redis si disponible
try:
    import django_redis
    REDIS_ENABLED = config('REDIS_ENABLED')
    
    if REDIS_ENABLED:
        CACHES['default'] = {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': config('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PASSWORD': config('REDIS_PASSWORD'),
            }
        }
        print("✅ Redis activé")
    else:
        print("⚠️ Cache mémoire activé (Redis désactivé)")
except ImportError:
    print("⚠️ django_redis non installé - Utilisation du cache mémoire")

WSGI_APPLICATION = 'market.wsgi.application'

# Désactiver l'avertissement de clé de cache trop longue
import warnings
from django.core.cache.backends.base import CacheKeyWarning
warnings.simplefilter("ignore", CacheKeyWarning)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# recuperation des parametres de l'API pawapay

PAWAPAY_API_TOKEN = config(
    "PAWAPAY_API_TOKEN"
)

PAWAPAY_BASE_URL = config(
    "PAWAPAY_BASE_URL",
    default="https://api.sandbox.pawapay.io"
)

PAWAPAY_CURRENCY = config(
    "PAWAPAY_CURRENCY",
    default="XAF"
)

PAWAPAY_COUNTRY = config(
    "PAWAPAY_COUNTRY",
    default="CMR"
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'users.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Créer le dossier logs
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Niveau de log selon l'environnement
LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'verbose': {
            'format': '{asctime} - {levelname} - {name} - {module} - {funcName} - {lineno} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} - {levelname} - {message}',
            'style': '{',
        },
        'json': {
            'format': '{{"timestamp": "{asctime}", "level": "{levelname}", "module": "{module}", "func": "{funcName}", "message": "{message}"}}',
            'style': '{',
        },
        'security': {
            'format': '{asctime} - [SECURITY] - {levelname} - {name} - {message}',
            'style': '{',
        },
        'business': {
            'format': '{asctime} - [BUSINESS] - {levelname} - {name} - User:{user} - Action:{message}',
            'style': '{',
        },
    },
    
    'handlers': {
        # Console
        'console': {
            'class': 'logging.StreamHandler',
            'level': LOG_LEVEL,
            'formatter': 'simple',
        },
        
        # Fichier global
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Fichier des erreurs
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'errors.log'),
            'maxBytes': 10485760,
            'backupCount': 10,
            'level': 'ERROR',
            'formatter': 'verbose',
        },
        
        # Sécurité (déconnexions, tentatives de hacking)
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'WARNING',
            'formatter': 'security',
        },
        
        # Performance (requêtes lentes, etc.)
        'performance_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'performance.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # === Logs par module ===
        
        # Authentification
        'auth_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'authentication.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Utilisateurs
        'user_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'user.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Produits
        'product_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'product.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Catégories
        'categorie_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'categorie.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Inventaire
        'inventory_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'inventory.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Mouvements de stock
        'stock_movement_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'stock_movement.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Commandes
        'order_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'order.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
        
        # Paiements
        'payment_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'payment.log'),
            'maxBytes': 10485760,
            'backupCount': 5,
            'level': 'INFO',
            'formatter': 'verbose',
        },
    },
    
    'loggers': {
        # === ROOT LOGGER ===
        '': {
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        
        # === MODULES SPÉCIFIQUES ===
        
        # Authentication
        'apps.authentication': {
            'handlers': ['console', 'auth_file', 'error_file', 'security_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # User
        'apps.users': {
            'handlers': ['console', 'user_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Product
        'apps.product': {
            'handlers': ['console', 'product_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Categorie
        'apps.categorie': {
            'handlers': ['console', 'categorie_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Inventory
        'apps.inventory': {
            'handlers': ['console', 'inventory_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # MouvementStock
        'apps.mouvement_Stock': {
            'handlers': ['console', 'stock_movement_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # # Commande
        # 'apps.commande': {
        #     'handlers': ['console', 'order_file', 'error_file'],
        #     'level': 'INFO',
        #     'propagate': False,
        # },
        
        # # Paiement
        # 'apps.paiement': {
        #     'handlers': ['console', 'payment_file', 'error_file', 'security_file'],
        #     'level': 'INFO',
        #     'propagate': False,
        # },
        
        # Core (middleware, utils)
        'apps.core': {
            'handlers': ['console', 'file', 'performance_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # === DJANGO ===
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'error_file', 'performance_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',  # Mettre DEBUG pour voir les requêtes SQL
            'propagate': False,
        },
    },
}